### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by hammady**
This adds Docker support to simplify running the example shiny app.
No prerequisites are required except having Docker installed.
The `README.md` is also updated with build/run instructions.

It also adds a new GitHub action to build and push the docker image to GitHub container registry.
This even simplifies running the shiny app further where users can simply pull the image instead of checking out the code and building it locally.

### CODE REVIEW

**Comment by chriscpritchard** [comment]
Hi,

Would you be able to add the ability to add a versioned docker container when a new github release is created?

I think that would be quite useful before merging?

Chris

**Comment by hammady** [comment]
> Would you be able to add the ability to add a versioned docker container when a new github release is created?
> 
> I think that would be quite useful before merging?

@chriscpritchard the action defined in this PR builds a docker image on every push to the `master` branch and tags it with the `latest` tag (docker tags). Moreover, any git tag that is pushed to that branch which starts with `v`, e.g. `v1.2.3` also tags the generated image with the version number, e.g. `1.2.3`. Please check [this repo](https://github.com/rayyansys/PRISMA2020/actions) for examples. So basically:
| git branch/tag | docker tag |
| ------ | ---------- |
| `master` | `latest` |
| `v1.2.3` | `1.2.3` |
| Anything else | No docker tag |

**Comment by chriscpritchard** [comment]
> 

Ah brill, I think I missed that! If you could rebase against main, I can look to merge!

**Comment by hammady** [comment]
@chriscpritchard No worries at all. I am planning to work on this PR again this week, I will let you know once rebased.

**Comment by hammady** [comment]
@chriscpritchard now rebased on `master`.

**Comment by chriscpritchard** [comment]
!deploy

**Comment by chriscpritchard** [comment]
Really sorry about the delay with all this - work is extremely busy! I'll need to update our deployment workflow to use the latest version of the action and then I can test and push this. Hopefully I'll have some capacity over the weekend for this!

**Comment by chriscpritchard** [comment]
Updated workflows so hopefully !deploy will work!

**Review by chriscpritchard — APPROVED** [review]
Approved

**Pull request merged**
